### ISSUE TITLE
ImportError while running tests

### ISSUE THREAD

**Issue by sprakashdash** [robinhenry/gym-anm#1]
When I run the test command: `python -m tests` I get the following error:
```
======================================================================
ERROR: test_dcopf_agent (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dcopf_agent
Traceback (most recent call last):
  File "/home/satan/miniconda3/envs/rl-algo-env/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/satan/miniconda3/envs/rl-algo-env/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/home/satan/Torch_Env_List/gym-anm/tests/test_dcopf_agent.py", line 6, in <module>
    from gym_anm import MPCAgent
ImportError: cannot import name 'MPCAgent' from 'gym_anm' (/home/satan/Torch_Env_List/gym-anm/gym_anm/__init__.py)


----------------------------------------------------------------------
Ran 82 tests in 10.757s

FAILED (errors=1)
```

**Comment by sprakashdash** [comment]
Created a PR #2 to resolve this!

**Comment by robinhenry** [comment]
Awesome, thanks!
